server:
  port: 8081
  servlet:
    context-path: /api/v1/

spring:
  application:
    name: ms-bill
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/ecommerce
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  auth:
    converter:
      resource-id: api-gateway-client
      principal-attribute: preferred_username
logging:
  level:
    org.springframework.security: DEBUG

security:
  oauth2:
    client:
      provider:
        keycloak:
          issuer-uri: http://localhost:8082/realms/ecommerce
      registration:
        keycloak:
          client-id: backend
          client-secret: 9zfKLLyI3wAOkmWuQLU6FHjl7l9lQQqI
          redirect-uri: http://localhost:8090/login/oauth2/code/keycloak

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true