server:
  port: 8090
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: ms-bill
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/**
        - id: users-service
          uri: http://localhost:8086
          predicates:
            - Path=/users/**
      discovery:
        locator:
          enabled: true
  security:
    oauth2:
      client:
        provider:
          gateway:
            issuer-uri: http://localhost:8082/realms/ecommerce
        registration:
          api-gateway-client:
            provider: gateway
            client-id: api-gateway-client
            client-secret: nbP8ZuJT0FgPd3xHohpv0QnHnXMg3J8r
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: 'http://localhost:8090/login/oauth2/code/keycloak'